### ISSUE TITLE
[Fixed] Not working in WebGL

### ISSUE THREAD

**Issue by gmrodriguez124** [H1M4W4R1/Unity-Aspect-Oriented-Programming#6]
Works as expected in editor, building to webgl and running produces no errors but doesn't execute code (as if it didn't exist)

**Comment by gmrodriguez124** [comment]
Modifying WeaveAssemblies (CodeProcessor.cs) directory path to:
`directoryPath = Application.dataPath + $"/../Library/Bee/PlayerScriptAssemblies/";`

causes an error:

```
Building Library\Bee\artifacts\WebGL\ManagedStripped failed with output:

C:\Program Files\Unity\Hub\Editor\2022.3.0f1\Editor\Data\il2cpp\build\deploy\UnityLinker.exe @Library\Bee\artifacts\rsp\4081997910746323624.rsp
Fatal error in Unity CIL Linker
Mono.Linker.LinkerFatalErrorException: ILLink: error IL1013: Error processing 'C:\Users\user\Documents\Unity Projects\projectname\Temp\StagingArea\Data\Managed\MethodsToPreserve.xml'
 ---> System.IO.IOException: The process cannot access the file 'C:\Users\user\Documents\Unity Projects\projectname\Library\Bee\PlayerScriptAssemblies\JasonSkillman.ScriptableEvents.dll' because it is being used by another process.
```

**Comment by gmrodriguez124** [comment]
Ok I fixed it by manually reverting the commit that enabled multi assembly dlls (but keeping the modified directory for WebGL)

I highly suspect that my antivirus was locking the file since about 5 minutes later it complained about some non-related dll - this has never happened before

I am going to open a branch later (either tonight or around the weekend) so that it can be merged

**Comment by H1M4W4R1** [comment]
Can you test this revision?
https://github.com/H1M4W4R1/Unity-Aspect-Oriented-Programming/commit/9799de6791eccfc0e4fc6546160dcd2e08465944

It still will collide with AV software, however now it should weave OpenGL assemblies. Also your version was incompatible with IL2CPP which generates DLLs under `Library/Bee/artifacts` instead of `Library/Bee/PlayerScriptAssemblies`.

**Comment by gmrodriguez124** [comment]
Sure, give me until late tonight as I've overwritten my previous test code. 

Also WebGL is _only_ compatible with the IL2CPP backend and I had tested with a WebGL build (2022.3.0). Perhaps it uses PlayerScriptAssemblies DLLS prior to generating the artifacts? Just a shot in the dark :)

Thanks btw

**Comment by gmrodriguez124** [comment]
On a sidenote, couldn't you just pass the assemblies string array from OnFilterAssemblies (EditorLevelAssemblyProcessor.cs)
directly into the weaver? I'd imagine that it contains all the dlls that are being processed - and therefore would account for every condition/build type.

I am not very knowledgeable in DLLs and code gen so this may be completely wrong.

**Comment by H1M4W4R1** [comment]
> Also WebGL is only compatible with the IL2CPP backend and I had tested with a WebGL build (2022.3.0). Perhaps it uses PlayerScriptAssemblies DLLS prior to generating the artifacts? Just a shot in the dark :)

I'm using 2021.3.21f1 (as it's default editor for currently developed project my client demands to use)

> On a sidenote, couldn't you just pass the assemblies string array from OnFilterAssemblies (EditorLevelAssemblyProcessor.cs)
directly into the weaver? I'd imagine that it contains all the dlls that are being processed - and therefore would account for every condition/build type.

You're right. This code is just 3 years old and was written while being... not too sober to fix one single irritating problem within a single project. However it's a good idea to improve it... Just dropped a commit with update.

> Sure, give me until late tonight as I've overwritten my previous test code.

Please provide timezone while writing hour / time of day... for me now it's middle of the night (precisely 2:36 AM UTC+2).

**Comment by gmrodriguez124** [comment]
I ended up having the same issue regarding the AV, I disabled it and the problem still occurred. 
I used (since my project wouldn't use this in another assembly anyways):

`assemblies.FirstOrDefault(s => s.Contains("Assembly-CSharp.dll"));`

so, it's definitely working. I have no idea why it fails on that one dll though and only when building (in editor it works just fine)

> Please provide timezone while writing hour / time of day... for me now it's middle of the night (precisely 2:36 AM UTC+2).

My entire team is situated in one timezone so I completely forgot this was a thing, apologies! I ended up bug fixing elsewhere that night so could never get to it anyways


I ran to some other issues that are unrelated but this info would help me deduce some stuff, does this use reflection at runtime? such as when providing propertyinfo in the baseexecutionargs - or is this cached somewhere?


Thanks for everything again!

**Comment by H1M4W4R1** [comment]
> Does this use reflection at runtime?

Probably you figured it out already, but yes it does. Mostly `MethodBase` class methods (Invoke, MakeGenericMethod), because going around this would require a bit of trickery.

> I have no idea why it fails on that one dll though and only when building (in editor it works just fine)

Editor and Player works a bit different way. It fails at linking, so probably weaving did pass, however for some 
reason assembly was not disposed after weaving. Maybe a circular reference?

> I ran to some other issues that are unrelated
Just drop them into separate GitHub Issues, will take a look w

hen I get some free time (impossible to determine approximate time). Less bugs are usually better.

**Comment by gmrodriguez124** [comment]
> Just drop them into separate GitHub Issues, will take a look when I get some free time (impossible to determine approximate time). Less bugs are usually better.

I fixed the issue, it was related to a separate system I was developing that dealt with reflection - il2cpp is aot so I wasn't sure if it was this or the stuff I was doing (it was) and was too lazy to make a separate project

If I ever get the time, I kind of want to attempt developing a CreateDelegate based system for your compile time code instead of the methodbase. It's basically what I ended up doing for my stuff except at runtime. Runtime is a nightmare.

**Comment by H1M4W4R1** [comment]
> If I ever get the time, I kind of want to attempt developing a CreateDelegate based system for your compile time code instead of the methodbase. It's basically what I ended up doing for my stuff except at runtime. Runtime is a nightmare.

Actually I meant splitting the AOP wrapper into two halves and implementing direct call to method rather than Invoke. ATM it uses single processing code for all methods, that's why MethodBase::Invoke is used. 

To be more precise:
Wrapper checks if method should be processed, then creates new (secondary) method with same body. Next step is to remove body from primary method and implements a call to AOPProcessor which calls that new method using MethodBase::Invoke. 

Alternative way is to split AOPProcessor calls into two (one before method call and one after) and call method directly in the primary, however it would require a bit of trickery to implement features like `return value override`.

**Comment by gmrodriguez124** [comment]
> Actually I meant splitting...

Just to confirm, as in you meant to do it that way but it's not right now? 

It's an interesting concept, I never realized until recently that code gen can literally change an entire class based on well another class. It's like a layer on top of it all.

**Comment by H1M4W4R1** [comment]
> Just to confirm, as in you meant to do it that way but it's not right now?

It was one of initial concepts, but why I choose current one with reflection ask me 3 years ago...

> It's an interesting concept, I never realized until recently that code gen can literally change an entire class based on well another class. It's like a layer on top of it all.

As long as you can fluently operate in IL, you can even make a self-rewriting game.
